services:
  front:
    image: w1-front
    build: .
    ports:
      - "3000:3000"
    environment:
      JWT_SECRET: "my-secret"
  back:
    image: "w1-back"
    ports:
      - "5000:5000"
    environment:
      JWT_SECRET: "my-secret"